# PostgreSQL database configuration
# Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres       # 改成你的 PostgreSQL 用户名
  password: 111111  # 改成你的 PostgreSQL 密码
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: demo_api_development

test:
  <<: *default
  database: demo_api_test

production:
  <<: *default
  database: demo_api_production
  username: demo_api
  password: <%= ENV["DEMO_API_DATABASE_PASSWORD"] %>

